version: '3.1'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password  # 替换为你的根密码
      MYSQL_DATABASE: my_database           # 创建的默认数据库
      MYSQL_USER: root                   # 替换为你的用户名
      MYSQL_PASSWORD: 123456         # 替换为你的用户密码
    ports:
      - "3306:3306"  # 映射端口
    volumes:
      - mysql_data:/var/lib/mysql  # 数据持久化

volumes:
  mysql_data:
